set_location_assignment PIN_N15 -to led[0]
set_location_assignment PIN_N14 -to led[1]
set_location_assignment PIN_M14 -to led[2]
set_location_assignment PIN_M12 -to led[3]
set_location_assignment PIN_J14 -to key[3]
set_location_assignment PIN_J11 -to key[2]
set_location_assignment PIN_K14 -to key[1]
set_location_assignment PIN_J9 -to key[0]
set_location_assignment PIN_J5 -to clk